#!/usr/bin/env bash
#============================================================================
# repo-add.sh — Create or update the Archmox Arch Linux binary repository
#============================================================================
set -euo pipefail

readonly SELF="$(realpath "$0")"
readonly ROOT="$(realpath "${SELF}/../..")"
readonly REPODIR="${ROOT}/repo"
readonly DBNAME="archmox"
readonly DBFILE="${REPODIR}/${DBNAME}.db.tar.zst"
readonly FILESFILE="${REPODIR}/${DBNAME}.files.tar.zst"

# Colors
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m'

log()   { echo -e "${GREEN}[REPO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
info()  { echo -e "${CYAN}[INFO]${NC} $*"; }

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  --clean     Remove all old packages and rebuild from scratch
  --sign      Sign packages with gpg before adding to repo
  --key <id>  GPG key ID to use for signing
  --help, -h  Show this help message

Environment:
  REPODIR     Custom repo directory (default: ${REPODIR})
  DBNAME      Custom database name (default: ${DBNAME})
EOF
  exit 0
}

sign_packages() {
  local key_id="$1"
  log "Signing all unsigned packages in ${REPODIR}..."
  for pkg in "${REPODIR}"/*.pkg.tar.zst; do
    [[ -f "${pkg}" ]] || continue
    if [[ ! -f "${pkg}.sig" ]]; then
      gpg --detach-sign --default-key "${key_id}" --no-armor "${pkg}"
      log "Signed: $(basename "${pkg}")"
    fi
  done
}

clean_repo() {
  warn "Cleaning repository directory ${REPODIR}..."
  rm -f "${REPODIR}"/*.pkg.tar.zst "${REPODIR}"/*.pkg.tar.zst.sig \
        "${REPODIR}/${DBNAME}.db.tar.zst" "${REPODIR}/${DBNAME}.db" \
        "${REPODIR}/${DBNAME}.files.tar.zst" "${REPODIR}/${DBNAME}.files"
  log "Repository cleaned."
}

main() {
  local clean=false
  local sign=false
  local gpg_key=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --clean)    clean=true ;;
      --sign)     sign=true ;;
      --key)      gpg_key="$2"; shift ;;
      --help|-h)  usage ;;
      *)          warn "Unknown option: $1"; usage ;;
    esac
    shift
  done

  mkdir -p "${REPODIR}"

  if [[ "${clean}" == true ]]; then
    clean_repo
  fi

  # Optionally re-sign all packages
  if [[ "${sign}" == true ]]; then
    if [[ -z "${gpg_key}" ]]; then
      gpg_key="${GPGKEY:-${GPGKEYID:-}}"
    fi
    if [[ -z "${gpg_key}" ]]; then
      error "No GPG key specified. Use --key <id> or set GPGKEY/GPGKEYID."
      exit 1
    fi
    sign_packages "${gpg_key}"
  fi

  # Count packages
  local pkg_count
  pkg_count="$(find "${REPODIR}" -maxdepth 1 -name '*.pkg.tar.zst' -type f | wc -l)"
  info "Found ${pkg_count} packages in ${REPODIR}"

  if [[ "${pkg_count}" -eq 0 ]]; then
    warn "No packages to add to repository."
    exit 0
  fi

  # Remove old database files so repo-add works cleanly
  rm -f "${DBFILE}" "${REPODIR}/${DBNAME}.db" \
        "${FILESFILE}" "${REPODIR}/${DBNAME}.files"

  log "Adding packages to repository '${DBNAME}'..."

  # Add all .pkg.tar.zst files (excluding signature files)
  # repo-add will automatically find and include .sig files
  repo-add --new --verify --sign \
    "${DBFILE}" \
    "${REPODIR}"/*.pkg.tar.zst

  log "Repository database updated successfully!"
  info "Database: ${DBFILE}"
  info "To use this repo, add to /etc/pacman.conf:"
  echo
  echo "  [${DBNAME}]"
  echo "  SigLevel = Optional TrustAll"
  echo "  Server = file://${REPODIR}"
  echo

  # Create a pacman.conf snippet for easy inclusion
  local conf_snippet="${REPODIR}/archmox.repo.conf"
  cat > "${conf_snippet}" <<-REPOCONF
# Archmox repository - generated by repo-add.sh
# Add to /etc/pacman.conf or include from a .conf.d directory

[${DBNAME}]
SigLevel = Optional TrustAll
Server = file://${REPODIR}
REPOCONF
  log "Pacman config snippet written to ${conf_snippet}"
}

main "$@"
