#!/usr/bin/env bash
#============================================================================
# customize_airootfs.sh — Post-install customization for Archmox ISO
#============================================================================
# This script runs inside the archiso chroot environment after packages
# are installed but before the squashfs image is created.

set -euo pipefail

echo "[ARCHMOX] Starting airootfs customization..."

#--------------------------------------------------------------------------
# System configuration
#--------------------------------------------------------------------------

# Set timezone to UTC
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# Generate locale
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Set hostname
echo "archmox" > /etc/hostname

# Configure hosts file
cat > /etc/hosts <<-EOF
127.0.0.1   localhost
::1         localhost
127.0.1.1   archmox.localdomain archmox
EOF

# Set root password to empty (user must set on first boot)
passwd -d root

# Create necessary Proxmox directories
mkdir -p /etc/pve
mkdir -p /var/lib/pve
mkdir -p /var/log/pve
mkdir -p /var/lib/vz
mkdir -p /var/lib/vz/images
mkdir -p /var/lib/vz/dump
mkdir -p /var/lib/vz/template
mkdir -p /var/lib/vz/template/cache
mkdir -p /var/lib/vz/template/iso

#--------------------------------------------------------------------------
# pacman configuration
#--------------------------------------------------------------------------

# Enable parallel downloads in pacman
sed -i 's/^#ParallelDownloads = 5/ParallelDownloads = 10/' /etc/pacman.conf
sed -i 's/^#Color/Color/' /etc/pacman.conf
sed -i 's/^#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf

# Enable multilib
if ! grep -q '^\[multilib\]' /etc/pacman.conf; then
  cat >> /etc/pacman.conf <<-EOF

[multilib]
Include = /etc/pacman.d/mirrorlist
EOF
fi

# Add Archmox repository if present
if [[ -d /opt/archmox-repo ]] && ls /opt/archmox-repo/*.pkg.tar.zst &>/dev/null 2>&1; then
  cat >> /etc/pacman.conf <<-EOF

[archmox]
SigLevel = Optional TrustAll
Server = file:///opt/archmox-repo
EOF
fi

# Update mirrorlist for speed
cat > /etc/pacman.d/mirrorlist <<-'EOF'
## Arch Linux mirrorlist generated by archmox installer
## Server = http://mirror.example.com/archlinux/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
Server = https://archlinux.mirror.constant.com/$repo/os/$arch
Server = https://mirror.us.leaseweb.net/archlinux/$repo/os/$arch
EOF

# Initialize pacman keyring and populate with Arch Linux keys
pacman-key --init
pacman-key --populate archlinux

#--------------------------------------------------------------------------
# GRUB configuration
#--------------------------------------------------------------------------

# Default GRUB settings for Proxmox
cat > /etc/default/grub <<-EOF
# Generated by Archmox installer
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="Archmox"
GRUB_CMDLINE_LINUX_DEFAULT="quiet systemd.show_status=1"
GRUB_CMDLINE_LINUX=""
GRUB_PRELOAD_MODULES="part_gpt part_msdos"
GRUB_TERMINAL_INPUT=console
GRUB_TERMINAL_OUTPUT=console
GRUB_GFXMODE=auto
GRUB_DISABLE_RECOVERY=true
GRUB_ENABLE_CRYPTODISK=y
GRUB_SAVEDEFAULT=true
EOF

#--------------------------------------------------------------------------
# Networking defaults
#--------------------------------------------------------------------------

# Enable IP forwarding for VMs/containers
cat > /etc/sysctl.d/99-archmox.conf <<-EOF
# Archmox networking optimizations
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.tcp_tw_reuse = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_congestion_control = bbr
net.core.default_qdisc = fq
vm.swappiness = 10
vm.min_free_kbytes = 1048576
EOF

# Default network configuration (DHCP)
cat > /etc/systemd/network/20-wired.network <<-EOF
[Match]
Name=en*

[Network]
DHCP=ipv4
DNS=1.1.1.1
DNS=8.8.8.8
EOF

# Disable predictable network naming for Proxmox compatibility
ln -sf /dev/null /etc/systemd/network/99-default.link

#--------------------------------------------------------------------------
# Proxmox-specific services and configs
#--------------------------------------------------------------------------

# Create systemd service overrides
mkdir -p /etc/systemd/system/pveproxy.service.d
cat > /etc/systemd/system/pveproxy.service.d/override.conf <<-EOF
[Service]
LimitNOFILE=65536
LimitNPROC=65536
EOF

mkdir -p /etc/systemd/system/pvedaemon.service.d
cat > /etc/systemd/system/pvedaemon.service.d/override.conf <<-EOF
[Service]
LimitNOFILE=65536
LimitNPROC=65536
EOF

# Set up log rotation for Proxmox logs
cat > /etc/logrotate.d/pve <<-EOF
/var/log/pve/*.log {
  weekly
  rotate 12
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
}
EOF

# Create /etc/archmox-release
cat > /etc/archmox-release <<-EOF
NAME="Archmox"
ID=archmox
PRETTY_NAME="Archmox (Proxmox on Arch Linux)"
VERSION_ID="${ARCHMOX_VERSION:-rolling}"
HOME_URL="https://archmox.acreetionos.org"
SUPPORT_URL="https://archmox.acreetionos.org/support"
BUG_REPORT_URL="https://github.com/archmox/archmox/issues"
EOF

#--------------------------------------------------------------------------
# User creation
#--------------------------------------------------------------------------

# Create 'admin' user with sudo privileges
useradd -m -G wheel,storage,libvirt,kvm,lxd -s /bin/bash admin 2>/dev/null || true
echo "admin:admin" | chpasswd

# Allow wheel group to sudo without password
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/10-wheel

# Create 'pve' user for Proxmox services
useradd -r -s /usr/sbin/nologin -d /var/lib/pve pve 2>/dev/null || true

#--------------------------------------------------------------------------
# Cleanup
#--------------------------------------------------------------------------

# Remove pacman cache
rm -rf /var/cache/pacman/pkg/*

# Remove SSH host keys (will be regenerated on first boot)
rm -f /etc/ssh/ssh_host_*

# Remove machine ID (will be regenerated on first boot)
rm -f /etc/machine-id
touch /etc/machine-id

# Clean temporary files
rm -rf /tmp/*

# Remove the offline repo if packages were installed from it
if ! mountpoint -q /opt/archmox-repo 2>/dev/null; then
  rm -rf /opt/archmox-repo
fi

echo "[ARCHMOX] airootfs customization complete!"
